In [2]:
import pandas as pd
import requests
import json

In [3]:
cities = pd.read_csv('CleanedSheet.csv')
cities.head()

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,ANDHRA PRADESH,ADILABAD,2001.0,101.0,60.0,17.0,50.0,0.0,50.0,46.0,...,30.0,1131.0,16.0,149.0,34.0,175.0,0.0,181.0,1518.0,4154.0
1,ANDHRA PRADESH,ANANTAPUR,2001.0,151.0,125.0,1.0,23.0,0.0,23.0,53.0,...,69.0,1543.0,7.0,118.0,24.0,154.0,0.0,270.0,754.0,4125.0
2,ANDHRA PRADESH,CHITTOOR,2001.0,101.0,57.0,2.0,27.0,0.0,27.0,59.0,...,38.0,2088.0,14.0,112.0,83.0,186.0,0.0,404.0,1262.0,5818.0
3,ANDHRA PRADESH,CUDDAPAH,2001.0,80.0,53.0,1.0,20.0,0.0,20.0,25.0,...,23.0,795.0,17.0,126.0,38.0,57.0,0.0,233.0,1181.0,3140.0
4,ANDHRA PRADESH,EAST GODAVARI,2001.0,82.0,67.0,1.0,23.0,0.0,23.0,49.0,...,41.0,1244.0,12.0,109.0,58.0,247.0,0.0,431.0,2313.0,6507.0

In [12]:
loc = cities[['STATE/UT', 'DISTRICT']]
loc.head()

         STATE/UT       DISTRICT
0  ANDHRA PRADESH       ADILABAD
1  ANDHRA PRADESH      ANANTAPUR
2  ANDHRA PRADESH       CHITTOOR
3  ANDHRA PRADESH       CUDDAPAH
4  ANDHRA PRADESH  EAST GODAVARI

In [14]:
loc['DISTRICT'].nunique()

825

In [55]:
def getCoordinates(location, cache, iteration):
    if location not in cache.keys():
        print("Not found in cache");
        params = {
            'key': 'ciGNJ4Y3fvsCmD3Wrnx8gG7RAWpAWzRg',
            'inFormat': 'kvp',
            'outFormat': 'json',
            'thumbMaps': 'false',
            'location': location
        }
        res = requests.get('http://www.mapquestapi.com/geocoding/v1/address', params=params)
        jsonResponse = res.json()
        print(location, jsonResponse)
        if len(jsonResponse['results'][0]['locations']) > 0:
            cache[location] = jsonResponse['results'][0]['locations'][0]['latLng']
    if iteration%10==0:
        print("Iteration {it} successful".format(it=iteration))
    return cache[location]

In [43]:
cache = {}
district = loc['DISTRICT']
state = loc['STATE/UT']
loc_arr = ["{dist}, {st}".format(dist=district[i], st=state[i]) for i in range(len(district))]

In [56]:
for count, elem in enumerate(loc_arr, 0):
    getCoordinates(elem, cache, count)

Iteration 0 successful
Iteration 10 successful
Iteration 20 successful
Iteration 30 successful
Iteration 40 successful
Iteration 50 successful
Iteration 60 successful
Iteration 70 successful
Iteration 80 successful
Iteration 90 successful
Iteration 100 successful
Iteration 110 successful
Iteration 120 successful
Iteration 130 successful
Not found in cache
AHMEDABAD COMMR., GUJARAT {'info': {'statuscode': 0, 'copyright': {'text': 'Â© 2020 MapQuest, Inc.', 'imageUrl': 'http://api.mqcdn.com/res/mqlogo.gif', 'imageAltText': 'Â© 2020 MapQuest, Inc.'}, 'messages': []}, 'options': {'maxResults': -1, 'thumbMaps': False, 'ignoreLatLngInput': False}, 'results': [{'providedLocation': {'location': 'AHMEDABAD COMMR., GUJARAT'}, 'locations': []}]}

TypeError: '>' not supported between instances of 'list' and 'int'