In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('SGD Project - Sheet1.csv')
df.head()
df.shape

(10677, 91)

In [3]:
df_removed_2014 = df[df['YEAR'] != 2014]
df_removed_2014.shape

(9875, 91)

In [4]:
df_removed_2014.isna()

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10647,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10649,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10652,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10672,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10674,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [5]:
df_col_rem = df_removed_2014.dropna(axis=1, how='all')
df_col_rem.shape

(9875, 33)

In [6]:
df_col_rem.isna()

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10647,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10649,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10652,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10672,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10674,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [7]:
df_col_rem.isna()

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10647,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10649,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10652,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10672,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10674,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [8]:
df_row_rem = df_col_rem.dropna(how='all')
df_row_rem.shape

(9385, 33)

In [9]:
df_row_rem.to_csv('CleanedSheet.csv', index=False)